services:
  web:
    image: php:8.2-apache
    container_name: php-apache-server
    ports:
      - "8080:80"
    volumes:
      - ./server:/var/www/html
    environment:
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000
